<a href="https://colab.research.google.com/github/PriyanshuChaudhary00/Ai/blob/main/Planar_Data_Classification_with_One_Hidden_Layer.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
from sklearn.datasets import make_moons
m = 500
X, y = make_moons(
    n_samples=m,
    noise=0.2,
    random_state=42
)

In [ ]:
# print(y[0])

In [ ]:
# import matplotlib.pyplot as plt

# plt.scatter(X[:,0], X[:,1], c=y)
# plt.show()

In [ ]:
def init_parameter(n_x , n_h , n_y):
  w1 = np.random.randn(n_h , n_x)*0.01
  b1 = np.zeros((n_h , 1))
  w2 = np.random.randn(n_y , n_h)*0.01
  b2 = np.zeros((n_y , 1))

  return w1 , b1 , w2 , b2

In [ ]:
w1 , b1 , w2 , b2 = init_parameter(2,4,1)
print(w1)
print(b1)
print(w2)
print(b2)

[[-0.00028095  0.00503809]
 [ 0.00937433 -0.00557949]
 [-0.01190307  0.01107751]
 [-0.00939819 -0.00648859]]
[[0.]
 [0.]
 [0.]
 [0.]]
[[ 0.0019569   0.0010026  -0.0103141  -0.01016298]]
[[0.]]


In [ ]:
def output(X , w1 , w2 , b1 , b2):
  z1 = w1 @ X.T + b1
  A1 = np.tanh(z1)
  z2 = w2 @ A1 + b2
  A2 = 1 / (1 + np.exp(-z2))
  return A1, A2

In [ ]:
def loss( y , A2):
  temp2 = 0
  for i in range(len(y)):
    temp = y[i] * np.log(A2[0, i]) + (1 - y[i])* np.log(1 - A2[0, i])
    temp2 += temp
  return -temp2/500

In [ ]:
loss(y , A2)

np.float64(0.6921408330907951)

In [ ]:
A1, A2 = output(X,w1,w2,b1,b2)

In [ ]:
def backward(A1 , A2 , y , X):
  dZ_2 = A2 - y

  dW_2 = (1/m)* (dZ_2 @ A1.T)

  dB_2 = (1/m)* (np.sum(dZ_2, axis=1, keepdims=True))

  dZ_1 = w2.T @ dZ_2 * (1 - np.power(A1, 2))

  dW_1 = (1/m)* dZ_1@X

  dB_1 = (1/m)*np.sum(dZ_1, axis=1, keepdims=True)
  return dW_1 , dB_1 , dW_2 , dB_2

In [ ]:
def gradient_descent(y , lr , w1 , w2 , b1 , b2 , dW_1 , dW_2 , dB_1 , dB_2):
  w1 = w1 - lr * dW_1
  b1 = b1 - lr * dB_1
  w2 = w2 - lr * dW_2
  b2 = b2 - lr * dB_2
  return w1 , b1 , w2 , b2


In [ ]:
for i in range(10000):

    A1 , A2 = output(X , w1 , w2 , b1 , b2)
    cost = loss(y , A2)
    dW_1 , dB_1 , dW_2 , dB_2 = backward(A1 , A2 , y , X)
    w1 , b1 , w2 , b2 = gradient_descent(y , 0.01 , w1 , w2 , b1 , b2 , dW_1 , dW_2 , dB_1 , dB_2)

    if i % 1000 == 0:
        print(f"Iteration {i}: Cost = {cost}")

Iteration 0: Cost = 0.6930806658485882
Iteration 5000: Cost = 0.2900188304340987
Iteration 10000: Cost = 0.2871733893156978
Iteration 15000: Cost = 0.2859924206576959
Iteration 20000: Cost = 0.28516339812724467
Iteration 25000: Cost = 0.2845502191450102
Iteration 30000: Cost = 0.2840751792576378
Iteration 35000: Cost = 0.2836937749372662
Iteration 40000: Cost = 0.2833788808039186
Iteration 45000: Cost = 0.2831125426328436


In [ ]:
pred = (A2 > 0.5)

In [ ]:
accuracy = np.mean(pred == y)
print("Model Accuracy: ",accuracy*100,"%")

Model Accuracy:  86.0 %
